apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: blue-green-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-app
      version: blue
  template:
    metadata:
      labels:
        app: prod-app
        version: blue
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
