apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: product
  labels:
    app: postgres
spec:
  type: ClusterIP  # Internal access only
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
