spring:
  application:
    name: mobile-bff
server:
  port: 8102

# Shared service configuration
shared-service:
  url: http://localhost:8100

logging:
  level:
    com.masterclass.patterns.bff.mobile: INFO
